### ISSUE TITLE
IsFeature implementation

### ISSUE THREAD

**Issue by gublan24** [umple-ucosp/umple#1881]
The keyword isFeature makes a mixset an optional feature to the mixset that its included in. if the mixset is a root mixset, which is not contained in any mixsets, then the feature is optional feature to the base of the software product line. For example, the mixset FeatureA will be optional feature for the base SPL. The mixset C will be an optional feature for the mixset B. 

isFeature is similar to put the statement `require [optional ... ] `in the "container"mixset, which contains the mixset having isFeature keyword.

As the mixset B is not a feature mixset, this should raise a warning stating something like "B is non-feature mixset and can not have optional feature mixsets"

```
mixset FeatureA {
  isFeature;
}

mixset A{
  
  mixset B {
    
    mixset C {
      isFeature;    
    }
  }
}



```

**Comment by TimLethbridge** [comment]
Was done with #1887
