### ISSUE TITLE
Downloading SVG file should target a new tab in UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple-ucosp/umple#1906]
In UmpleOnline, If a user clicks on "Download the SVG file for the following", the system opens the diagram at the same working tab. If the user wants to go back to the code/design page, there is no such option. Moreover, if the user uses the browser back button, it redirects to an entirely new page. All the previous works/codes are lost.

**Steps to produce:**
(1) Select a class diagram such as "Afghan Rain Design".
![image](https://user-images.githubusercontent.com/82404135/142802059-5f4fa9dd-1053-41ef-abb3-4a199f25273c.png)
(2) Navigate to the "GENERATE" section and select "Entity Relationship Diagram (GraphViz SVG)" from the dropdown. Click on "Generate It".
![image](https://user-images.githubusercontent.com/82404135/142802149-b9708476-bfaf-4be6-8dc7-ca204630a9e3.png)
(3) Scroll a bit down and click on the "Download the SVG file for the following".
![image](https://user-images.githubusercontent.com/82404135/142802211-b050b2d7-21e3-4df2-9803-3d66979dc5ee.png)
(4) The system opens the diagram at the same working tab (In Google Chrome).
![image](https://user-images.githubusercontent.com/82404135/142802265-733b0d88-7114-4876-b968-01981ff8fae9.png)
(5) (In Google Chrome) Click on the browser back button, and the system will return to a completely new code/design page.
![image](https://user-images.githubusercontent.com/82404135/142802561-9237ba60-076c-4986-9cee-d75105500490.png)

**Expected:**
(1) The system should display the SVG in a separate browser tab.

**Solution**

 In all the 5 lines in compiler.php (lines 448, 473, 494, 515, 1398) that have "Download the SVG...", add target=\"svgfile\" between the a and the href . Raise as an issue. This would be a 10 minute fix.

**Comment by TimLethbridge** [comment]
Fixed by #2087
