### ISSUE TITLE
Methods in JointJS does not work for UmpleOnline

### ISSUE THREAD

**Issue by shoevancar** [umple-ucosp/umple#1915]
In UmpleOnline, users can switch between different viewing options for any sample umple code. If a user selects JointJs as a viewing option and then tries to show "methods", the system does not load respond as expected. This issue is similar to issue #1864 

**Steps to produce:**
(1) Select "Class Diagrams" >> Select any example such as "2DShapes".
(2) Go to the "OPTIONS". Then select "JointJS" from the diagram type.
(3) Click on the checkbox right of the Show View >> "Methods".
(4) Now, the system will fall into an error and will not load the diagram pane.

**Expected:**
(1) The system should display the diagram with methods (if available). Or, alternatively, the option to show methods should be hidden (this might be the easiest path).

Note: Joint.js is causing lots of trouble, so another option is simply to wihtdraw the functionality

**Comment by TimLethbridge** [comment]
Closing because I don't want to do further work on joint.js
