### ISSUE TITLE
Chinese gambling site linked in manuel

### ISSUE THREAD

**Issue by nikecocola** [umple-ucosp/umple#1970]
Hello, 
please regard  State Machines / Nested State Machines in the manuel ("https://cruise.umple.org/umple/NestedStateMachines.html"). In a comment you can find a link to the following webpage:
www.lloseng.com

Unfortunately this link leads to an asian gambling and porn site. Please fix.

**Comment by TimLethbridge** [comment]
This change has been made. @nikecocola thanks! The actual website will be updated shortly.
