### ISSUE TITLE
Compiler analysis failure when there is a duplicate association in a subclass, and also a further superclass.

### ISSUE THREAD

**Issue by nbagaria** [umple-ucosp/umple#2040]
[Show/Hide errors and warnings](https://cruise.umple.org/umpleonline/#)
Error on [line -1](javascript:Action.setCaretPosition(-1);Action.updateLineNumberDisplay();) : Compiler Error (Analysis). Could not analyze Umple model. Please report an issue with this entire message and your input code to Umple developers. Stack Trace Follows. To locate the error in the Umple source, set GeneratedSourcePath to root directory where the generated Java is located: e.g. setenv GeneratedSourcePath ~/umple/cruise.umple/src-gen-umple/ Exception java.lang.NullPointerException in at cruise.umple.compiler.UmpleInternalParser.checkIgnoredAssociations(UmpleInternalParser.java:4380) at cruise.umple.compiler.UmpleInternalParser.postTokenClassAnalysis(UmpleInternalParser.java:2569) at cruise.umple.compiler.UmpleInternalParser.postTokenAnalysis(UmpleInternalParser.java:1583) at cruise.umple.compiler.UmpleInternalParser.analyze(UmpleInternalParser.java:1361) at cruise.umple.compiler.UmpleModel.run(UmpleModel.java:1757) at cruise.umple.PlaygroundMain.processCommand(PlaygroundMain.java:833) at cruise.umple.PlaygroundMain.handleMessageFromClient(PlaygroundMain.java:473) at cruise.umple.AbstractServer.receiveMessageFromClient(AbstractServer.java:557) at cruise.umple.ConnectionToClient.run(ConnectionToClient.java:335) . [More information (9100)](http://manual.umple.org/?E9x00CompilerError.html)

**Comment by TimLethbridge** [comment]
Thanks, but I need you to provide the code ... this error message is not enough (the message says 'and your input code'

Tim

**Comment by nbagaria** [comment]
Dear Professor

Here is the code a

(link commented out for copyright reasons)

Nam

**Comment by TimLethbridge** [comment]
I am hiding the code to prevent violation of the author's copyright, but I will boil it down shortly

**Comment by nbagaria** [comment]
Ok thank you

**Comment by TimLethbridge** [comment]
I have isolated the bug. @nbagaria you can work around this by changing lines 111 and 112 of your code to be the following

```
  1 fo -- * Facilitators;
  1 mo -- * Motivators;
```

That doesn't exuse the bug, but this workaround of adding role names solves the problem (by the way use G mode to make the diagram look nice)

**Comment by TimLethbridge** [comment]
The following is concise code that reproduces the problem:

```
class X {
  isA Y;
}

class Y {
  isA Z;
}

class Z {
}

class Outcome {
  1 -- * Y;
  1 -- * X;
}
```

Adding role names after  the 1 in the last two associations solves the problem. But this should not cause a failure. To investigate with priority.

**Comment by TimLethbridge** [comment]
The bug occurs with the following code too, where the associations are specified in the class on the other end.

```
class X {
  isA Y;
  * -- 1 Outcome;

}

class Y {
  isA Z;
  * -- 1 Outcome;
}

class Z {
}

class Outcome {
}
```

The bug does not occur if the superclass Z is removed. The bug has to do with searching up the hierarchy for duplicate associations that are inherited. The search works fine, except, it seems, when the search goes into a class such as Z here that is 'above' the top level where the associations are introduced.

**Comment by TimLethbridge** [comment]
Conclusion. The normal process is that if an inherited association is duplicated in a subclass, then it is ignored. This was not working in this case, where there is another superclass in the chain. A pull request has been prepared.
