### ISSUE TITLE
Requirements with the same name should be combined as mixins

### ISSUE THREAD

**Issue by TimLethbridge** [umple-ucosp/umple#2053]
This is a sub-issue of #1865 which is the main issue for the requirements feature.

Currently, if two req statements are encountered with the same name, an error is printed. However, in fact if for all of them if there is no conflict in language (same language, or no language, or the same langauge for some and no language for others) then the requrements should be combined in the same way that mixins of classes are combined.

Note that the 'printing' of messages is separately addressed in issue #2052

**Comment by vybhavigururaj** [comment]
It was discovered that the model is designed in a way that each identifier is mapped only to one requirement. Each time there is a new requirement encountered for the identifier the latest one replaces the earlier one.  This leaves us with 2 design decisions
1) **Change the model to take a list of requirements** - This will allow each identifier to store a list of requirements mapping to it. The drawback is that the whole model must be changed and passed through.
2) **Concatenate the requirements** - This is an easy fix but only requirements of the same language must be concatenated. If the requirements are in different languages a warning statement must be printed. One drawback is that there is no way of maintaining the order of the requirements if they are just concatenated. There must be some kind of numbering/ordering that would need to be introduced either automatically or manually.
